[package]
name = "pb"
version = "2.3.3"
edition = "2021"

[build-dependencies]
tonic-build = { version = "0.9.2", features = ["prost"] }

[dependencies]
prost = "0.12.4"
tonic = "0.11.0"
tonic-build = { version = "0.11.0", features = ["prost"] }
