[package]
name = "cm-pb-rs"
version = "2.3.5"
edition = "2021"

[build-dependencies]
tonic-build = { version = "0.12.1", features = ["prost"] }

[dependencies]
prost = "0.13.1"
prost-types = "0.13.1"
